### ISSUE TITLE
Preprocessor Guard Naming Conflicts with Other Libraries "QUEUE_H"

### ISSUE THREAD

**Issue by RoscoeTheDog** [sdesalas/Arduino-Queue.h#6]
some enviroment details...
```
PlatformIO
Arduino-ESP framework
board: ESP32-S2-Saola-1
```

When including this library into my platformIO project, the header's preprocessor guards conflict with the standard C _queue_ library, causing me to get unexpected behavior from intellisence such as `Queue is not a templated class" (when it clearly is).

Changing it to `QUEUE_H_2` fixed the issue, although this was just a placeholder name. I'm sure you can find a better name for it. Funny enough, I'd suggest changing it to something _less_ generic simply because this is a third-party library and it seems to conflict with the arduino API and other ports of the arduino framework across some other boards.

**Comment by sdesalas** [comment]
Thanks good point!

**Comment by sdesalas** [comment]
Straight to `master`!
